package com.maiky.bitacora.ui.theme

import androidx.compose.ui.graphics.Color

// Blue Theme
val BluePrimary = Color(0xFF1976D2)
val BlueOnPrimary = Color(0xFFFFFFFF)
val BluePrimaryContainer = Color(0xFFD1E4FF)
val BlueOnPrimaryContainer = Color(0xFF001D36)
val BlueSecondary = Color(0xFF535F70)
val BlueOnSecondary = Color(0xFFFFFFFF)
val BlueSecondaryContainer = Color(0xFFD7E3F7)
val BlueOnSecondaryContainer = Color(0xFF101C2B)
val BlueTertiary = Color(0xFF6B5778)
val BlueOnTertiary = Color(0xFFFFFFFF)
val BlueTertiaryContainer = Color(0xFFF2DAFF)
val BlueOnTertiaryContainer = Color(0xFF251431)

val BlueDarkPrimary = Color(0xFF9ECAFF)
val BlueDarkOnPrimary = Color(0xFF003258)
val BlueDarkPrimaryContainer = Color(0xFF00497D)
val BlueDarkOnPrimaryContainer = Color(0xFFD1E4FF)
val BlueDarkSecondary = Color(0xFFBBC7DB)
val BlueDarkOnSecondary = Color(0xFF253140)
val BlueDarkSecondaryContainer = Color(0xFF3B4858)
val BlueDarkOnSecondaryContainer = Color(0xFFD7E3F7)

// Purple Theme
val PurplePrimary = Color(0xFF6750A4)
val PurpleOnPrimary = Color(0xFFFFFFFF)
val PurplePrimaryContainer = Color(0xFFEADDFF)
val PurpleOnPrimaryContainer = Color(0xFF21005D)
val PurpleSecondary = Color(0xFF625B71)
val PurpleOnSecondary = Color(0xFFFFFFFF)
val PurpleSecondaryContainer = Color(0xFFE8DEF8)
val PurpleOnSecondaryContainer = Color(0xFF1D192B)
val PurpleTertiary = Color(0xFF7D5260)
val PurpleOnTertiary = Color(0xFFFFFFFF)
val PurpleTertiaryContainer = Color(0xFFFFD8E4)
val PurpleOnTertiaryContainer = Color(0xFF31111D)

val PurpleDarkPrimary = Color(0xFFD0BCFF)
val PurpleDarkOnPrimary = Color(0xFF381E72)
val PurpleDarkPrimaryContainer = Color(0xFF4F378B)
val PurpleDarkOnPrimaryContainer = Color(0xFFEADDFF)
val PurpleDarkSecondary = Color(0xFFCCC2DC)
val PurpleDarkOnSecondary = Color(0xFF332D41)
val PurpleDarkSecondaryContainer = Color(0xFF4A4458)
val PurpleDarkOnSecondaryContainer = Color(0xFFE8DEF8)

// Green Theme
val GreenPrimary = Color(0xFF388E3C)
val GreenOnPrimary = Color(0xFFFFFFFF)
val GreenPrimaryContainer = Color(0xFFA8F5A2)
val GreenOnPrimaryContainer = Color(0xFF002204)
val GreenSecondary = Color(0xFF52634F)
val GreenOnSecondary = Color(0xFFFFFFFF)
val GreenSecondaryContainer = Color(0xFFD5E8CF)
val GreenOnSecondaryContainer = Color(0xFF101F10)
val GreenTertiary = Color(0xFF38656A)
val GreenOnTertiary = Color(0xFFFFFFFF)
val GreenTertiaryContainer = Color(0xFFBCEBF1)
val GreenOnTertiaryContainer = Color(0xFF002023)

val GreenDarkPrimary = Color(0xFF8DDB88)
val GreenDarkOnPrimary = Color(0xFF00390A)
val GreenDarkPrimaryContainer = Color(0xFF005314)
val GreenDarkOnPrimaryContainer = Color(0xFFA8F5A2)
val GreenDarkSecondary = Color(0xFFB9CCB4)
val GreenDarkOnSecondary = Color(0xFF253424)
val GreenDarkSecondaryContainer = Color(0xFF3B4B39)
val GreenDarkOnSecondaryContainer = Color(0xFFD5E8CF)

// Red Theme
val RedPrimary = Color(0xFFD32F2F)
val RedOnPrimary = Color(0xFFFFFFFF)
val RedPrimaryContainer = Color(0xFFFFDAD6)
val RedOnPrimaryContainer = Color(0xFF410002)
val RedSecondary = Color(0xFF775653)
val RedOnSecondary = Color(0xFFFFFFFF)
val RedSecondaryContainer = Color(0xFFFFDAD6)
val RedOnSecondaryContainer = Color(0xFF2C1513)
val RedTertiary = Color(0xFF755A2F)
val RedOnTertiary = Color(0xFFFFFFFF)
val RedTertiaryContainer = Color(0xFFFFDDB0)
val RedOnTertiaryContainer = Color(0xFF281800)

val RedDarkPrimary = Color(0xFFFFB4AB)
val RedDarkOnPrimary = Color(0xFF690005)
val RedDarkPrimaryContainer = Color(0xFF93000A)
val RedDarkOnPrimaryContainer = Color(0xFFFFDAD6)
val RedDarkSecondary = Color(0xFFE7BDB8)
val RedDarkOnSecondary = Color(0xFF442927)
val RedDarkSecondaryContainer = Color(0xFF5D3F3C)
val RedDarkOnSecondaryContainer = Color(0xFFFFDAD6)

// Common
val CommonError = Color(0xFFB3261E)
val CommonOnError = Color(0xFFFFFFFF)
val CommonErrorContainer = Color(0xFFF9DEDC)
val CommonOnErrorContainer = Color(0xFF410E0B)

val CommonDarkError = Color(0xFFF2B8B5)
val CommonDarkOnError = Color(0xFF601410)
val CommonDarkErrorContainer = Color(0xFF8C1D18)
val CommonDarkOnErrorContainer = Color(0xFFF9DEDC)

val LightBackground = Color(0xFFFFFBFE)
val LightOnBackground = Color(0xFF1C1B1F)
val LightSurface = Color(0xFFFFFBFE)
val LightOnSurface = Color(0xFF1C1B1F)
val LightSurfaceVariant = Color(0xFFE7E0EC)
val LightOnSurfaceVariant = Color(0xFF49454F)
val LightOutline = Color(0xFF79747E)

val DarkBackground = Color(0xFF1C1B1F)
val DarkOnBackground = Color(0xFFE6E1E5)
val DarkSurface = Color(0xFF1C1B1F)
val DarkOnSurface = Color(0xFFE6E1E5)
val DarkSurfaceVariant = Color(0xFF49454F)
val DarkOnSurfaceVariant = Color(0xFFCAC4D0)
val DarkOutline = Color(0xFF938F99)

val CompletedGreen = Color(0xFF4CAF50)
val PendingOrange = Color(0xFFFF9800)

// Category colors
val CategoryTrabajo = Color(0xFF1976D2)
val CategoryEscuela = Color(0xFF7B1FA2)
val CategoryPersonal = Color(0xFF388E3C)
val CategorySalud = Color(0xFFD32F2F)
val CategoryReuniones = Color(0xFFF57C00)
